### ISSUE TITLE
Day-18 Challenge working in codedamn compiler ??

### ISSUE THREAD

**Issue by prince214** [kishanrajput23/50-Days-of-JavaScript#1]
Hi there !
Is your Day-18 Challenge working in the codedamn compiler ?? My code seems to working in my local. But not working in the codedamn compiler. I also tried your but not working.

**Comment by kishanrajput23** [comment]
Yes,
I also checked now my code also not working in Codedamn compiler. I've updated my day 18 solution, you can refer it. 
Now it will work.

**Comment by prince214** [comment]
Yes, working now. 👍
